### ISSUE TITLE
Allow multiple blocks

### ISSUE THREAD

**Issue by Soreine** [Soreine/draftjs-diff#1]
Hitting enter for example, will create new blocks. So we need to handle multiple blocks. It would probably be faster too.

**Comment by johanneslumpe** [comment]
In order to do this we will have to use content states as the base of comparison rather than just plain text. This requires that we figure out a way how to efficiently and logically sound map blocks to each other, even if someone inserts a new block within two blocks.

**Comment by Soreine** [comment]
This was fixed on master by converting whole texts diffs in list of ranges relative to beginning of each block.
